roles:
  - name: fail2ban
    src: git+git@github.com:rockdarko/fail2ban.git
    version: master
  - name: inspq_vmsetup
    src: git+git@github.com:rockdarko/inspq_vmsetup.git
    version: main
collections:
  - name: jonellis.sudoers